#! /bin/bash

R_HOME=$( dirname $0 )
BABS_PROJECT_HOME=`readlink -f $PWD`
RENV_PATHS_ROOT=[set path]
ADDITIONAL_PATHS=[set path]
TMP=/tmp
PYTHON_PATH=$( readlink -f ${PWD}/env/bin )

MOUNTS=${BABS_PROJECT_HOME},${RENV_PATHS_ROOT},${TMP}
if [ ! -z "$ADDITIONAL_PATHS" ]; then
	MOUNTS=$MOUNTS,$ADDITIONAL_PATHS
fi

SINGULARITY_ENVS="BABS_PROJECT_HOME=${BABS_PROJECT_HOME},PREPEND_PATH=${PYTHON_PATH}"

module load Singularity/3.6.4;

print_help ( ) {
    echo "USAGE: R-rocker -p [command line option string to R] [R script file]\n\n"
    echo " * Running R-rocker with no commandline parameters will give you an R shell."
    echo " * Specifying an R script file will run Rscript."
    echo " * Use the -p flag to define the command line argument string to pass to either Rscript or R."
    echo " * Run 'R-rocker container' to get a singularlity shell."
    exit
}

while getopts p:h flag
do
    case "${flag}" in
    	p) params=${OPTARG};;
	h) print_help
    esac
done

if [ -z ${1+x} ]; then
     singularity exec \
                --bind ${MOUNTS} \
                --pwd ${BABS_PROJECT_HOME} \
                --containall \
                --cleanenv \
		--env ${SINGULARITY_ENVS} \
                ./rockerimage.sif R
elif [ $1 == "container" ]; then
    singularity shell \
		--bind ${MOUNTS} \
                --pwd ${BABS_PROJECT_HOME} \
                --containall \
                --cleanenv \
		--env ${SINGULARITY_ENVS} \
                ./rockerimage.sif
elif [ -e $1 ]; then
    singularity exec \
                --bind ${MOUNTS} \
                --pwd ${BABS_PROJECT_HOME} \
                --containall \
                --cleanenv \
		--env ${SINGULARITY_ENVS} \
                ./rockerimage.sif Rscript ${params} $1
else
    singularity exec \
                --bind ${MOUNTS} \
                --pwd ${BABS_PROJECT_HOME} \
                --containall \
                --cleanenv \
		--env ${SINGULARITY_ENVS} \
                ./rockerimage.sif R -e ${params} "$1"
    exit
fi
